package com.example.whybackend.dao;

import com.example.whybackend.HotQuestion;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface HotQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_question
     *
     * @mbg.generated
     */
    int insert(HotQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_question
     *
     * @mbg.generated
     */
    int insertSelective(HotQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_question
     *
     * @mbg.generated
     */
    List<HotQuestion> getHotQuestionList();
    HotQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotQuestion record);
}