package com.example.whybackend.dao;

import com.example.whybackend.Idea;

public interface IdeaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated
     */
    int insert(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated
     */
    int insertSelective(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated
     */
    Idea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Idea record);
}